### PR TITLE
Updating the software tutorial

### PR DESCRIPTION
**Pull request by LindseyArndt**
I switched to the raspberry pi 4 using the raspberry pi imager instead of Ubuntu MATE. I also added new screenshots for the pi imager and command line. I also changed the order of when to place the SD card in and when to combine all the parts together and turn it on. I also changed some formatting by adding in numbered steps and bolding some words to hopefully make it easier to read and understand. I also made the steps a list item to differentiate the steps from the description of the step.

### CODE REVIEW

**Comment by abislam123** [comment]
Alright I went through the beats and everything looks sound. The only thing that might need changing is the order of the screenshots if they are to be taken as the order the directions should be followed. The last three screenshots would do better if they were put after the OS imager. If you plan on ordering it later everything looks good

**Comment by adampbeardsley** [comment]
Just remembered this morning - we should also add instructions for installing jupyter so folks can look at data as they take it.

**Comment by adampbeardsley** [comment]
@abislam123 could you clarify what you mean by the ordering? The last three screenshots are about navigating to the example directories, which is in line with the instructions. We're not sure what you mean by moving them to the imager section. Do they not appear in this order for you?

**Comment by abislam123** [comment]
So if I'm understanding this correctly, for me the last three screenshots are creating the example files then going to the terminal. I feel those should go before the third  screenshot that's currently there. Would it be better if I sent pictures of what I'm seeing and understanding?

**Comment by adampbeardsley** [comment]
Ok, I think I understand what's happening here. Are you looking at the screenshots right on the github PR? If that's the case, it shows them to you in alphabetic order, not in the order they would appear on the website. 

To see the website as it's being proposed, you need to clone the repo to your local machine, checkout this branch, then open the software.html file in a browser. Lindsay or I could help you get it set up if you need it.

**Comment by abislam123** [comment]
Alright this makes a lot more sense. Apologies for the confusion. I'll try to figure out how do the steps you outlined and I'll let you or Lindsay know if I need help. If all goes well, I'll have the new edits reviewed

**Comment by abislam123** [comment]
I looked over the changes and everything looks good. It all flows together nicely.

**Review by adampbeardsley — APPROVED** [review]

**Pull request merged**
